/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/atikul/.choosenim/toolchains/nim-0.18.0/lib -o /Users/atikul/GitHub/projects/nim/nimcache/rockPaperScissor.o /Users/atikul/GitHub/projects/nim/nimcache/rockPaperScissor.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NimStringDesc* tyArray_24KAM9afIUgUaqBaEBB6r9bg[3];
N_LIB_PRIVATE N_NIMCALL(void, randomize_RtUZt2O8eA6Y5pFWOsdgjg)(void);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, GAME_9cbdY2UQvwydycN7uuyRAkQ)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(NI, rand_F1qFFP53BvbP4L65Kn9bG1w_2)(NI max);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, nossleep)(NI milsecs);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_bKoQGynT9bWCEn79aXG8be9aw)(NimStringDesc* s, NimStringDesc* sub);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_kqueueInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_kqueueDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, rockPaperScissorDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_3, "\012A GAME MADE BY MOHAMMAD ISLAM\012*The purpose of this program is "
"to create a complicated game of Rock, Paper, Scissors, Lizard, S"
"pock.\012* The game is made to be played against the Computer. \012* T"
"he Computer input is fully random \012\012\012The winner is Chosen by the"
" follwing rules \012- Rock blunts Scissors, and Lizard \012- Paper cov"
"ers Rock, disproves Spock \012- Scissors cuts Paper, decapitates Li"
"zard \012- Lizard piosons Spock, eats Paper \012- Spock smashes Scisso"
"rs, vaporizes Rock\012***\012Press \"q\" and \"Enter\" in any point to exi"
"t the game...\012___     ___     ___    \012\\  \\    \\  \\    \\  \\   \012 \\"
"  \\    \\  \\    \\  \\  \012  )  )    )  )    )  ) \012 /  /    /  /    /"
"  /  \012/__/    /__/    /__/", 665);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_2 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_3)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_4, "", 0);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_5, "n", 1);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_7, "                     -----\012\012\012Rock (r), Paper (p), Scissors (s),"
" Lizard (l), Spock (sp)\?  ", 89);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_6 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_7)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_8, "sp", 2);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_9, "p", 1);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_10, "l", 1);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_11, "s", 1);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_12, "r", 1);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_13, "q", 1);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_14, "who", 3);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_15, "Spock", 5);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_16, "Paper", 5);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_17, "Lizard", 6);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_18, "Scissors", 8);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_19, "Rock", 4);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_21, "me", 2);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_20 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_21)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_22, "invalid_input", 13);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_23, " vs ", 4);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_25, "  _|_|          _|_|_|    _|_|    _|      _|  _|_|_|_|      _| "
"     _|    _|_|    _|_|_|    _|_|_|_|      _|_|_|    _|      _| "
"\012_|    _|      _|        _|    _|  _|_|  _|_|  _|            _|_"
"|  _|_|  _|    _|  _|    _|  _|            _|    _|    _|  _|\012_|"
"_|_|_|      _|  _|_|  _|_|_|_|  _|  _|  _|  _|_|_|        _|  _|"
"  _|  _|_|_|_|  _|    _|  _|_|_|        _|_|_|        _|\012_|    _"
"|      _|    _|  _|    _|  _|      _|  _|            _|      _| "
" _|    _|  _|    _|  _|            _|    _|      _|\012_|    _|    "
"    _|_|_|  _|    _|  _|      _|  _|_|_|_|      _|      _|  _|  "
"  _|  _|_|_|    _|_|_|_|      _|_|_|        _|    _|\012           "
"                                                                "
"                                                 _|\012\012\012_|      _|"
"    _|_|    _|    _|    _|_|    _|      _|  _|      _|    _|_|  "
"  _|_|_|        _|_|_|    _|_|_|  _|          _|_|    _|      _|"
"\012_|_|  _|_|  _|    _|  _|    _|  _|    _|  _|_|  _|_|  _|_|  _|_"
"|  _|    _|  _|    _|        _|    _|        _|        _|    _| "
" _|_|  _|_|\012_|  _|  _|  _|    _|  _|_|_|_|  _|_|_|_|  _|  _|  _|"
"  _|  _|  _|  _|_|_|_|  _|    _|        _|      _|_|    _|      "
"  _|_|_|_|  _|  _|  _|\012_|      _|  _|    _|  _|    _|  _|    _| "
" _|      _|  _|      _|  _|    _|  _|    _|        _|          _"
"|  _|        _|    _|  _|      _|\012_|      _|    _|_|    _|    _|"
"  _|    _|  _|      _|  _|      _|  _|    _|  _|_|_|        _|_|"
"_|  _|_|_|    _|_|_|_|  _|    _|  _|      _|  ", 1453);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_24 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_25)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_27, "It\"s a DRAW!", 12);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_26 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_27)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_29, "player wins!", 12);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_28 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_29)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_31, "Computer wins!", 14);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_30 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_31)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_33, "Invalid user input, Computer wins!", 34);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_32 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_33)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_35, "\012Please provide letters only!.\012Key of \"Enter\" and numbers are n"
"ot considered an option!\012", 88);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_34 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_35)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_37, "\012\012Do you want to try again\? YES (y) or No (n)\?  ", 48);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_36 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_37)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_38, "y", 1);
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_40, "\012THANKS FOR TRYING OUT MY GAME...\012", 34);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_39 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_40)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_42, "...", 3);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_41 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_42)}
;
STRING_LITERAL(TM_bqimUy3wz9ckOBW7k9bCs5EA_44, "Sorry your input was counted as no!", 35);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_bqimUy3wz9ckOBW7k9bCs5EA_43 = {((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_44)}
;

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, GAME_9cbdY2UQvwydycN7uuyRAkQ)(void) {
	NimStringDesc* stop;
	nimfr_("GAME", "rockPaperScissor.nim");
	nimln_(37, "rockPaperScissor.nim");
	stop = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_4));
	{
		nimln_(38, "rockPaperScissor.nim");
		while (1) {
			NimStringDesc* player;
			NimStringDesc* Computer;
			NI Chosen;
			nimln_(398, "system.nim");
			nimln_(38, "rockPaperScissor.nim");
			if (!!(eqStrings(stop, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_5)))) goto LA2;
			nimln_(40, "rockPaperScissor.nim");
			echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_6, 1);
			nimln_(42, "rockPaperScissor.nim");
			player = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
			Computer = (NimStringDesc*)0;
			nimln_(44, "rockPaperScissor.nim");
			Chosen = rand_F1qFFP53BvbP4L65Kn9bG1w_2(((NI) 6));
			nimln_(47, "rockPaperScissor.nim");
			{
				NimStringDesc* T7_;
				tyArray_24KAM9afIUgUaqBaEBB6r9bg T39_;
				if (!(((NI) 0) < (player ? player->Sup.len : 0))) goto LA5_;
				nimln_(50, "rockPaperScissor.nim");
				T7_ = (NimStringDesc*)0;
				T7_ = nsuToLowerAsciiStr(player);
				if (eqStrings(T7_, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_8))) goto LA8_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_9))) goto LA9_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_10))) goto LA10_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_11))) goto LA11_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_12))) goto LA12_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_13))) goto LA13_;
				if (eqStrings(T7_, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_14))) goto LA14_;
				goto LA15_;
				LA8_: ;
				{
					nimln_(52, "rockPaperScissor.nim");
					player = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_15));
				}
				goto LA16_;
				LA9_: ;
				{
					nimln_(54, "rockPaperScissor.nim");
					player = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_16));
				}
				goto LA16_;
				LA10_: ;
				{
					nimln_(56, "rockPaperScissor.nim");
					player = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_17));
				}
				goto LA16_;
				LA11_: ;
				{
					nimln_(58, "rockPaperScissor.nim");
					player = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_18));
				}
				goto LA16_;
				LA12_: ;
				{
					nimln_(60, "rockPaperScissor.nim");
					player = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_19));
				}
				goto LA16_;
				LA13_: ;
				{
					nimln_(1500, "system.nim");
					exit(((NI) 0));
				}
				goto LA16_;
				LA14_: ;
				{
					nimln_(64, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_20, 1);
				}
				goto LA16_;
				LA15_: ;
				{
					nimln_(66, "rockPaperScissor.nim");
					player = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_22));
				}
				LA16_: ;
				nimln_(72, "rockPaperScissor.nim");
				{
					if (!(Chosen == ((NI) 1))) goto LA27_;
					nimln_(73, "rockPaperScissor.nim");
					Computer = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_19));
				}
				goto LA25_;
				LA27_: ;
				{
					nimln_(74, "rockPaperScissor.nim");
					if (!(Chosen == ((NI) 2))) goto LA30_;
					nimln_(75, "rockPaperScissor.nim");
					Computer = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_16));
				}
				goto LA25_;
				LA30_: ;
				{
					nimln_(76, "rockPaperScissor.nim");
					if (!(Chosen == ((NI) 3))) goto LA33_;
					nimln_(77, "rockPaperScissor.nim");
					Computer = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_18));
				}
				goto LA25_;
				LA33_: ;
				{
					nimln_(78, "rockPaperScissor.nim");
					if (!(Chosen == ((NI) 4))) goto LA36_;
					nimln_(79, "rockPaperScissor.nim");
					Computer = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_17));
				}
				goto LA25_;
				LA36_: ;
				{
					nimln_(81, "rockPaperScissor.nim");
					Computer = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_15));
				}
				LA25_: ;
				nimln_(83, "rockPaperScissor.nim");
				memset((void*)T39_, 0, sizeof(T39_));
				T39_[0] = copyString(player);
				T39_[1] = copyString(((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_23));
				T39_[2] = copyString(Computer);
				echoBinSafe(T39_, 3);
				nimln_(84, "rockPaperScissor.nim");
				nossleep(((NI) 1000));
				nimln_(87, "rockPaperScissor.nim");
				{
					if (!eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_14))) goto LA42_;
					nimln_(88, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_24, 1);
				}
				goto LA40_;
				LA42_: ;
				{
					nimln_(90, "rockPaperScissor.nim");
					if (!eqStrings(player, Computer)) goto LA45_;
					nimln_(91, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_26, 1);
				}
				goto LA40_;
				LA45_: ;
				{
					NIM_BOOL T48_;
					nimln_(92, "rockPaperScissor.nim");
					T48_ = (NIM_BOOL)0;
					T48_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_19));
					if (!(T48_)) goto LA49_;
					T48_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_18));
					LA49_: ;
					if (!T48_) goto LA50_;
					nimln_(93, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_28, 1);
				}
				goto LA40_;
				LA50_: ;
				{
					NIM_BOOL T53_;
					nimln_(94, "rockPaperScissor.nim");
					T53_ = (NIM_BOOL)0;
					T53_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_19));
					if (!(T53_)) goto LA54_;
					T53_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_16));
					LA54_: ;
					if (!T53_) goto LA55_;
					nimln_(95, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_30, 1);
				}
				goto LA40_;
				LA55_: ;
				{
					NIM_BOOL T58_;
					nimln_(96, "rockPaperScissor.nim");
					T58_ = (NIM_BOOL)0;
					T58_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_19));
					if (!(T58_)) goto LA59_;
					T58_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_17));
					LA59_: ;
					if (!T58_) goto LA60_;
					nimln_(97, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_28, 1);
				}
				goto LA40_;
				LA60_: ;
				{
					NIM_BOOL T63_;
					nimln_(98, "rockPaperScissor.nim");
					T63_ = (NIM_BOOL)0;
					T63_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_19));
					if (!(T63_)) goto LA64_;
					T63_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_15));
					LA64_: ;
					if (!T63_) goto LA65_;
					nimln_(99, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_30, 1);
				}
				goto LA40_;
				LA65_: ;
				{
					NIM_BOOL T68_;
					nimln_(101, "rockPaperScissor.nim");
					T68_ = (NIM_BOOL)0;
					T68_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_16));
					if (!(T68_)) goto LA69_;
					T68_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_19));
					LA69_: ;
					if (!T68_) goto LA70_;
					nimln_(102, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_28, 1);
				}
				goto LA40_;
				LA70_: ;
				{
					NIM_BOOL T73_;
					nimln_(103, "rockPaperScissor.nim");
					T73_ = (NIM_BOOL)0;
					T73_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_16));
					if (!(T73_)) goto LA74_;
					T73_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_18));
					LA74_: ;
					if (!T73_) goto LA75_;
					nimln_(104, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_30, 1);
				}
				goto LA40_;
				LA75_: ;
				{
					NIM_BOOL T78_;
					nimln_(105, "rockPaperScissor.nim");
					T78_ = (NIM_BOOL)0;
					T78_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_16));
					if (!(T78_)) goto LA79_;
					T78_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_15));
					LA79_: ;
					if (!T78_) goto LA80_;
					nimln_(106, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_28, 1);
				}
				goto LA40_;
				LA80_: ;
				{
					NIM_BOOL T83_;
					nimln_(107, "rockPaperScissor.nim");
					T83_ = (NIM_BOOL)0;
					T83_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_16));
					if (!(T83_)) goto LA84_;
					T83_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_17));
					LA84_: ;
					if (!T83_) goto LA85_;
					nimln_(108, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_30, 1);
				}
				goto LA40_;
				LA85_: ;
				{
					NIM_BOOL T88_;
					nimln_(110, "rockPaperScissor.nim");
					T88_ = (NIM_BOOL)0;
					T88_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_18));
					if (!(T88_)) goto LA89_;
					T88_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_16));
					LA89_: ;
					if (!T88_) goto LA90_;
					nimln_(111, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_28, 1);
				}
				goto LA40_;
				LA90_: ;
				{
					NIM_BOOL T93_;
					nimln_(112, "rockPaperScissor.nim");
					T93_ = (NIM_BOOL)0;
					T93_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_18));
					if (!(T93_)) goto LA94_;
					T93_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_19));
					LA94_: ;
					if (!T93_) goto LA95_;
					nimln_(113, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_30, 1);
				}
				goto LA40_;
				LA95_: ;
				{
					NIM_BOOL T98_;
					nimln_(114, "rockPaperScissor.nim");
					T98_ = (NIM_BOOL)0;
					T98_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_18));
					if (!(T98_)) goto LA99_;
					T98_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_17));
					LA99_: ;
					if (!T98_) goto LA100_;
					nimln_(115, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_28, 1);
				}
				goto LA40_;
				LA100_: ;
				{
					NIM_BOOL T103_;
					nimln_(116, "rockPaperScissor.nim");
					T103_ = (NIM_BOOL)0;
					T103_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_18));
					if (!(T103_)) goto LA104_;
					T103_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_15));
					LA104_: ;
					if (!T103_) goto LA105_;
					nimln_(117, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_30, 1);
				}
				goto LA40_;
				LA105_: ;
				{
					NIM_BOOL T108_;
					nimln_(119, "rockPaperScissor.nim");
					T108_ = (NIM_BOOL)0;
					T108_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_17));
					if (!(T108_)) goto LA109_;
					T108_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_16));
					LA109_: ;
					if (!T108_) goto LA110_;
					nimln_(120, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_28, 1);
				}
				goto LA40_;
				LA110_: ;
				{
					NIM_BOOL T113_;
					nimln_(121, "rockPaperScissor.nim");
					T113_ = (NIM_BOOL)0;
					T113_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_17));
					if (!(T113_)) goto LA114_;
					T113_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_19));
					LA114_: ;
					if (!T113_) goto LA115_;
					nimln_(122, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_28, 1);
				}
				goto LA40_;
				LA115_: ;
				{
					NIM_BOOL T118_;
					nimln_(123, "rockPaperScissor.nim");
					T118_ = (NIM_BOOL)0;
					T118_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_17));
					if (!(T118_)) goto LA119_;
					T118_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_18));
					LA119_: ;
					if (!T118_) goto LA120_;
					nimln_(124, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_30, 1);
				}
				goto LA40_;
				LA120_: ;
				{
					NIM_BOOL T123_;
					nimln_(125, "rockPaperScissor.nim");
					T123_ = (NIM_BOOL)0;
					T123_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_17));
					if (!(T123_)) goto LA124_;
					T123_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_15));
					LA124_: ;
					if (!T123_) goto LA125_;
					nimln_(126, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_30, 1);
				}
				goto LA40_;
				LA125_: ;
				{
					NIM_BOOL T128_;
					nimln_(128, "rockPaperScissor.nim");
					T128_ = (NIM_BOOL)0;
					T128_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_15));
					if (!(T128_)) goto LA129_;
					T128_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_16));
					LA129_: ;
					if (!T128_) goto LA130_;
					nimln_(129, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_30, 1);
				}
				goto LA40_;
				LA130_: ;
				{
					NIM_BOOL T133_;
					nimln_(130, "rockPaperScissor.nim");
					T133_ = (NIM_BOOL)0;
					T133_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_15));
					if (!(T133_)) goto LA134_;
					T133_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_19));
					LA134_: ;
					if (!T133_) goto LA135_;
					nimln_(131, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_28, 1);
				}
				goto LA40_;
				LA135_: ;
				{
					NIM_BOOL T138_;
					nimln_(132, "rockPaperScissor.nim");
					T138_ = (NIM_BOOL)0;
					T138_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_15));
					if (!(T138_)) goto LA139_;
					T138_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_18));
					LA139_: ;
					if (!T138_) goto LA140_;
					nimln_(133, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_28, 1);
				}
				goto LA40_;
				LA140_: ;
				{
					NIM_BOOL T143_;
					nimln_(134, "rockPaperScissor.nim");
					T143_ = (NIM_BOOL)0;
					T143_ = eqStrings(player, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_15));
					if (!(T143_)) goto LA144_;
					T143_ = eqStrings(Computer, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_17));
					LA144_: ;
					if (!T143_) goto LA145_;
					nimln_(135, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_30, 1);
				}
				goto LA40_;
				LA145_: ;
				{
					nimln_(137, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_32, 1);
				}
				LA40_: ;
				nimln_(138, "rockPaperScissor.nim");
				nossleep(((NI) 1000));
			}
			goto LA3_;
			LA5_: ;
			{
				nimln_(141, "rockPaperScissor.nim");
				echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_34, 1);
			}
			LA3_: ;
			nimln_(143, "rockPaperScissor.nim");
			echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_36, 1);
			nimln_(144, "rockPaperScissor.nim");
			stop = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
			nimln_(145, "rockPaperScissor.nim");
			{
				NIM_BOOL T151_;
				NIM_BOOL T152_;
				T151_ = (NIM_BOOL)0;
				T152_ = (NIM_BOOL)0;
				T152_ = contains_bKoQGynT9bWCEn79aXG8be9aw(stop, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_5));
				if (T152_) goto LA153_;
				T152_ = contains_bKoQGynT9bWCEn79aXG8be9aw(stop, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_13));
				LA153_: ;
				T151_ = T152_;
				if (T151_) goto LA154_;
				T151_ = contains_bKoQGynT9bWCEn79aXG8be9aw(stop, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_38));
				LA154_: ;
				if (!T151_) goto LA155_;
				nimln_(146, "rockPaperScissor.nim");
				{
					NIM_BOOL T159_;
					T159_ = (NIM_BOOL)0;
					T159_ = contains_bKoQGynT9bWCEn79aXG8be9aw(stop, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_5));
					if (T159_) goto LA160_;
					T159_ = contains_bKoQGynT9bWCEn79aXG8be9aw(stop, ((NimStringDesc*) &TM_bqimUy3wz9ckOBW7k9bCs5EA_13));
					LA160_: ;
					if (!T159_) goto LA161_;
					nimln_(147, "rockPaperScissor.nim");
					nossleep(((NI) 1000));
					nimln_(148, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_39, 1);
					nimln_(149, "rockPaperScissor.nim");
					nossleep(((NI) 1000));
					nimln_(1500, "system.nim");
					exit(((NI) 0));
				}
				goto LA157_;
				LA161_: ;
				{
					nimln_(152, "rockPaperScissor.nim");
					echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_41, 1);
				}
				LA157_: ;
			}
			goto LA149_;
			LA155_: ;
			{
				nimln_(154, "rockPaperScissor.nim");
				echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_43, 1);
				nimln_(1500, "system.nim");
				exit(((NI) 0));
			}
			LA149_: ;
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_hashesDatInit000();
	stdlib_strtabsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_cpuinfoDatInit000();
	stdlib_kqueueDatInit000();
	stdlib_osprocDatInit000();
	stdlib_randomDatInit000();
	rockPaperScissorDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_hashesInit000();
	stdlib_strtabsInit000();
	stdlib_streamsInit000();
	stdlib_cpuinfoInit000();
	stdlib_kqueueInit000();
	stdlib_osprocInit000();
	stdlib_randomInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("rockPaperScissor", "rockPaperScissor.nim");
	nimln_(22, "rockPaperScissor.nim");
	randomize_RtUZt2O8eA6Y5pFWOsdgjg();
	nimln_(30, "rockPaperScissor.nim");
	echoBinSafe(TM_bqimUy3wz9ckOBW7k9bCs5EA_2, 1);
	nimln_(157, "rockPaperScissor.nim");
	GAME_9cbdY2UQvwydycN7uuyRAkQ();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, rockPaperScissorDatInit000)(void) {
}

